---
# Tasks for routing-private
- name: Routing-Private - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Routing-Private - Gather facts about Public subnet 2b
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ pub_sub_name_b }}"
  register: subnet_id_c

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_a.subnets[0].id

- name: Gateways - Gather facts about private subnet 2b
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ pri_sub_name_b }}"
  register: subnet_id_d

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_b.subnets[0].id

- name: Routing-Private - Gather Facts about NAT gateway in 2B
  local_action:
    module: ec2_vpc_nat_gateway_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region}}"
    filters:
      subnet-id: "{{ subnet_id_c.subnets[0].id }}"
      state: ['available']
  register: nat_gateway_2b

- name: Export NAT Gateway ID for future use
  debug:
   var: nat_gateway_2b.result[0].nat_gateway_id


- name: Routing-Private - New routing table for private subnet 2b
  local_action:
    module: ec2_vpc_route_table
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpcdata.vpcs[0].id }}"
    region: "{{ aws_region }}"
    tags:
      Name: Private Routing Table 2B
    subnets: "{{ subnet_id_c.subnets[0].id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway_2b.result[0].nat_gateway_id }}"
  register: private_route_table_2b