---
# Tasks for routing-public
- name: Routing-Public - Gather facts about my VPC
  local_action:
    module: ec2_vpc_net_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Routing-Public - Gather facts Internet Gateways
  local_action:
    module: ec2_vpc_igw_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: igw_facts

- name: Export IGW ID for future use
  debug:
   var: igw_facts.internet_gateways[0].internet_gateway_id

- name: Routing-Public - Gather facts about public subnets
  local_action:
    module: ec2_vpc_subnet_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpcdata.vpcs[0].id }}"
      "tag:Name": "{{ item }}"
  with_items:
    - Public_Subnet_2A
    - Public_Subnet_2B
    - Public_Subnet_2C
  register: public_subnet_facts

- set_fact:
    subnet_ids: "{{ public_subnet_facts.results|map(attribute='id')|list }}"

- name: Routing-Public - New routing table for public subnets
  local_action:
    module: ec2_vpc_route_table
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpcdata.vpcs[0].id }}"
    region: "{{ aws_region }}"
    tags:
      Name: Public Route table
    subnets:
      - "{{ subnet_id_a.subnets[0].id }}"
      - "{{ subnet_id_b.subnets[0].id }}"
      - "{{ subnet_id_c.subnets[0].id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_facts.internet_gateways[0].internet_gateway_id }}"
  register: public_route_table
