---
- name: s3 - creating S3 Bucket
  aws_s3:
    bucket: "{{ bucket_name }}"
    mode: create
    permission: private
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
# tasks file for utm
#- name: utm - creating S3 Bucket
#  s3_bucket:
#    name:  "{{ bucket_name }}"
#    region: us-west-2
#    state: present
#    versioning: no
#    policy: "{{ lookup('file,'policy.json')) }}"
