---
# Tasks for setting up NAT Gateways
- name: Gateways - Gather facts about my VPC
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpcdata

- name: Export VPC ID for future use
  debug:
   var: vpcdata.vpcs[0].id

- name: Gateways - Gather facts Internet Gateways
  ec2_vpc_igw_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: igw_facts

- name: Export IGW ID for future use
  debug:
   var: igw_facts.internet_gateways[0].internet_gateway_id

- name: Gateways - Gather facts about Public subnet A
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ pub_sub_name_a }}"
  register: subnet_id_a

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_a.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 1 of 3 ***These take time***
  ec2_vpc_nat_gateway:
    state: present
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    subnet_id: "{{ subnet_id_a.subnets[0].id }}"
    wait: no
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2a

- name: Gateways - Gather facts about public subnet 2b
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ pub_sub_name_b }}"
  register: subnet_id_b

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_b.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 2 of 3 ***These take time***
  ec2_vpc_nat_gateway:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    subnet_id: "{{ subnet_id_b.subnets[0].id }}"
    wait: no
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2b

- name: Gateways - Gather facts about public subnet 2c
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ pub_sub_name_c }}"
  register: subnet_id_c

- name: Export Subnet ID for future use
  debug:
   var: subnet_id_c.subnets[0].id

- name: Gateways - NAT Gateway and new EIP 3 of 3 ***These take time***
  ec2_vpc_nat_gateway:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    subnet_id: "{{ subnet_id_c.subnets[0].id }}"
    wait: yes
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway_2c
